CMU-Crowd/CMU-Crowd/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import main, workers, admins

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', main.SignUpView.as_view(), name='signup'),
    path('accounts/signup/worker/', workers.WorkerSignUpView.as_view(), name='worker_signup'),
    path('accounts/signup/admin/', admins.AdminSignUpView.as_view(), name='admin_signup'),
    path('admin/', admin.site.urls),
]

CMU-Crowd/main/urls.py
from django.urls import include, path
from .views import main, workers, admins
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", main.home, name='home'),
    path('workers/', include(([
        path('', workers.dash, name='dash'),
        path('view_annotations', workers.view_annotations, name='view_annotations'),
        path('view_jobs', workers.view_jobs, name='view_jobs'),
        path('jobs/<job_id>', workers.jobs, name="jobs")
    ], 'main'), namespace='workers')),
    path('admins/', include(([
        path('', admins.panel, name='panel'),
        path('job/add/', admins.JobCreateView.as_view(), name="create_job"),
        path('job/update/<int:pk>', admins.JobUpdateView.as_view(), name='update_job'),
        path('job/delete/<int:pk>', admins.JobDeleteView.as_view(), name='delete_job'),
        path('batch/start/', admins.BatchCreateView.as_view(), name="start_batch"),
        path('batches', admins.view_batches, name="view_batches"),
        path('update_batch/<batch_id>', admins.update_batch, name="update_batch"),
        path('manage_workers', admins.manage_workers, name="manage_workers")
    ], 'main'), namespace='admins')),

]


if settings.DEBUG: #development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CMU-Crowd/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


#MARK: User Models
class User(AbstractUser):
    is_worker = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

#Admin  #1-to-1 with user
class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.username


#Worker #1-to-1 with user
class Worker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    time_worked = models.IntegerField(default=0)
    is_approved = models.BooleanField(default=False)
    is_suspended = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Job(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    hourly_pay = models.DecimalField(decimal_places=2, max_digits=5)
    admins = models.ManyToManyField(Admin)
    html_template = models.FileField(upload_to="job_templates")

    def __str__(self):
        return self.title

class Batch(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    job = models.ForeignKey(Job, on_delete=models.PROTECT)
    content = models.TextField()
    num_HITs = models.IntegerField(default=10)
    is_completed = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    num_completed = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.job} / Batch ID {self.id}'

class Annotation(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    worker = models.ForeignKey(Worker, null=True, on_delete=models.SET_NULL)
    batch = models.ForeignKey(Batch, on_delete=models.PROTECT)
    batch_content_index = models.IntegerField()
    content = models.TextField()

    def __str__(self):
        return f' {self.batch} / {self.worker}'

CMU-Crowd/main/forms.py
import json
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from main.models import Worker, Admin, User, Job, Batch


class WorkerSignUpForm(UserCreationForm):

  class Meta(UserCreationForm.Meta):
        model = User

        @transaction.atomic #ensures sent in 1 transaction
        def save(self):
            user = super().save(commit=False)
            user.is_worker = True
            user.save()
            worker = Worker.objects.create(user=user)
            return user

class AdminSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User

        @transaction.atomic #ensures sent in 1 transaction
        def save(self):
            user = super().save(commit=False)
            user.is_admin = True
            user.save()
            worker = Admin.objects.create(user=user)
            return user

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ('title', 'description', 'hourly_pay', 'html_template')

class BatchForm(forms.ModelForm):

    content = forms.CharField(widget=forms.Textarea,required=False)

    class Meta:
        model = Batch
        fields = ('job', 'content', 'num_HITs')
        #validation
    def clean_content(self):
        data = self.cleaned_data['content']
        if data != "": #some content provided
            try:
                json.loads(data)
            except:
                raise forms.ValidationError("Please enter a valid JSON.")
        return data

CMU-Crowd/main/views/admins.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect,render,get_object_or_404
from django.views.generic import CreateView,UpdateView,DeleteView
from main.models import User,Job,Admin,Batch,Worker,Annotation
from ..forms import AdminSignUpForm,BatchForm
from ..decorators import admin_required

import pdb


class AdminSignUpView(CreateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('home')

@login_required
@admin_required
def panel(request):
    admin = Admin.objects.get(user=request.user)

    context = {"active_job_count":Job.objects.filter(admins=admin).count()}
    return render(request, 'main/admins/panel.html', context)




@method_decorator([login_required, admin_required], name='dispatch')
class JobCreateView(CreateView):
    model = Job
    fields = ('title','description','hourly_pay','html_template',)
    template_name = 'main/admins/create_job.html'

    def form_valid(self,form):
        job = form.save(commit=True)
        admin = Admin.objects.get(user=self.request.user)
        job.admins.add(admin)
        job.save()
        messages.success(self.request, "Job created successfully.")
        return redirect('admins:panel')

@method_decorator([login_required, admin_required], name='dispatch')
class JobUpdateView(UpdateView):
    model = Job
    fields = ('title','description','hourly_pay','html_template',)
    template_name = 'main/admins/update_job.html'

    def form_valid(self,form):
        job = form.save(commit=True)
        job.save()
        messages.success(self.request,"Job updated successfully.")
        return redirect('admins:panel')

@method_decorator([login_required, admin_required], name='dispatch')
class JobDeleteView(DeleteView):
    model = Job
    template_name = 'main/admins/confirm_delete_job.html'
    success_url = '/'



@method_decorator([login_required, admin_required], name='dispatch')
class BatchCreateView(CreateView):
    model = Batch
    form_class = BatchForm
    #fields = ('job','content','num_HITs')
    template_name = "main/admins/create_batch_form.html"

    def form_invalid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)
        context["errors"] = context["form"].errors
        return self.render_to_response(context)

    def form_valid(self, form):
        batch = form.save(commit=True)
        messages.success(self.request,"Batch created successfully.")
        return redirect('admins:panel')

@login_required
@admin_required
def update_batch(request, batch_id):
    batch = get_object_or_404(Batch, id=batch_id)
    action = request.POST.get('action')
    if action == 'cancel':
        batch.is_cancelled = True
    elif action == 'restart':
        batch.is_cancelled = False
    batch.save()
    return redirect('admins:view_batches')

@login_required
@admin_required
def view_batches(request):

    def batch_status_class(batch):
        if batch.is_cancelled:
            return 'danger'
        elif batch.is_completed:
            return 'success'
        else: #active batch
            return 'primary'
    def batch_statistics(batch):
        stats = dict()
        stats['id'] = batch.id
        stats['num_HITs'] = batch.num_HITs
        stats['created_date'] = batch.created_date
        num_completed = Annotation.objects.filter(batch=batch).count()
        stats['percent_completion'] = (num_completed / batch.num_HITs) * 100
        stats['cancelled'] = batch.is_cancelled
        stats['completed'] = batch.is_completed
        stats['status_class'] = batch_status_class(batch)
        return stats

    admin = Admin.objects.get(user=request.user)
    admin_jobs = admin.job_set.all()
    admin_batches = dict()
    jobs = dict()
    for j in admin_jobs:
        batch_stats = [batch_statistics(b) for b in Batch.objects.filter(job=j)]
        admin_batches[j.title] = batch_stats
        jobs[j.title] = j.id
    context = {'batches':admin_batches, 'jobs':jobs}
    return render(request, 'main/admins/view_batches.html', context)

@login_required
@admin_required
def manage_workers(request):
    def worker_statistics(worker):
        stats = dict()
        stats['id'] = worker.user.id
        stats['username'] = worker.user.username
        stats['date_joined'] = worker.user.date_joined
        stats['num_anns'] = Annotation.objects.filter(worker=worker).count()
        return stats

    workers = [worker_statistics(w) for w in Worker.objects.all()]
    context = {'workers':workers}

    return render(request, 'main/admins/manage_workers.html', context)

CMU-Crowd/main/views/workers.py
from django.contrib.auth import login
from django.shortcuts import redirect,render
from django.views.generic import CreateView
from main.models import User,Job,Annotation,Batch,Worker
from ..forms import WorkerSignUpForm
from django.template import Context, Template
from django.conf import settings
import json
import pdb

class WorkerSignUpView(CreateView):
    model = User
    form_class = WorkerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'worker'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('accounts/login')


def dash(request):
    worker = Worker.objects.get(user=request.user)
    work_done = Annotation.objects.filter(worker=worker).count()
    context = {'work_done':work_done,
               'last_job': None,
               'admin_email':settings.CONTACT_EMAIL
               }
    if work_done > 0:
        last_job_done = Annotation.objects.filter(worker=worker).last().batch.job
        context['last_job'] = last_job_done
    return render(request, 'main/workers/dash.html', context)


def view_jobs(request):
    jobs = Job.objects.all()
    context = {"jobs":jobs}
    return render(request, 'main/workers/view_jobs.html', context)

def view_annotations(request):
    worker = Worker.objects.get(user=request.user)
    annotations = Annotation.objects.filter(worker=worker)
    context = {"annotations":annotations}
    return render(request,'main/workers/view_annotations.html', context)

def batches_complete(job):
    batches = Batch.objects.filter(job=job)
    done = [b.is_completed or b.is_cancelled for b in batches]
    return all(done)


def jobs(request, job_id):
    job = Job.objects.get(id=job_id)
    if batches_complete(job):
        return render(request, 'main/workers/job_complete.html')

    template_url = job.html_template.url
    render_url = template_url.replace("/media/", "") #remove /media/ prefix
    #Oldest batch not completed && cancelled
    current_batch = (Batch.objects.filter(job=job).filter(is_completed=False)
                     .filter(is_cancelled=False).first())
    batch_content = json.loads(current_batch.content)
    if request.method == 'POST':
        content_dict = {k: v for k, v in request.POST.items()
                        if k != 'csrfmiddlewaretoken'} #remove csrftoken
        worker = Worker.objects.get(user=request.user)

        #Create annotation object
        Annotation.objects.create(
            worker=worker,
            batch=current_batch,
            batch_content_index=current_batch.num_completed,
            content=json.dumps(content_dict),
            )
        current_batch.num_completed += 1
        current_batch.save()
        if current_batch.num_completed == current_batch.num_HITs:
            current_batch.is_completed = True
            current_batch.save()
    context = batch_content[current_batch.num_completed]
    return render(request, render_url, context)

CMU-Crowd/main/templates/main/admins/confirm_delete_job.html
{% extends 'base.html' %}
{% block title %} Delete Job {% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h2> Delete Job </h2>
    </div>
  </div>
  <form  method="post">
	{% csrf_token %}
	 Are you sure you want to delete this job?
	 <input  type="submit"  value="Confirm"  />
  </form>
</div>
{% endblock %}

CMU-Crowd/main/templates/main/admins/create_batch_form.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}Create Batch{% endblock %}
{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
          {% if errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for fieldname,error in errors.items %}
        <p {% if forloop.last %} class="mb-0"{% endif %}>{{fieldname | title }} field: {{error }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}
        <h2> Create Batch</h2>
      </div>
    </div>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% for field in form %}
       <div class="form-row">
          <div class="form-group col-md-12">
            {{field.label}}
            {{field| addcss:'form-control'}}
             {%if form.title.errors %}
             <div class="alert alert-danger" style="margin-top:10px" role="alert">
             {{ form.title.errors }}
            </div>
             {% endif %}
            </div>
       </div>
       {% endfor %}
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

CMU-Crowd/main/templates/main/admins/create_job.html
{% extends 'base.html' %}
{% block title %}Create Job{% endblock %}

{% block content %}
  {% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for error in form.non_field_errors %}
        <p {% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}

<div class="container">
  <div class="row">
    <div class="col">
      <h2> Create Job </h2>
    </div>
  </div>
  {% include 'main/admins/job_form.html' %}
</div>
{% endblock %}

CMU-Crowd/main/templates/main/admins/job_form.html
{% load custom_tags %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}">
  {% for field in form %}
    <div class="form-row">
      <div class="form-group col-md-12">
        {{field.label}}
        {{field| addcss:'form-control'}}
        {%if form.title.errors %}
          <div class="alert alert-danger" style="margin-top:10px" role="alert">
            {{ form.title.errors }}
          </div>
        {% endif %}
      </div>
    </div>
       {% endfor %}
    <button type="submit" class="btn btn-success">Submit</button>
</form>

CMU-Crowd/main/templates/main/admins/manage_workers.html
{% extends 'base.html' %}
{% block title %}Manage Workers{% endblock %}
{% block content %}
<h1 class="text-center"> Manage Workers </h1>
<hr />
<div class="container">
  <div class="row">
   <div class="col">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Username</th>
          <th scope="col">Number of Annotations</th>
          <th scope="col">Date Joined</th>
          <th scope="col"> Status </th>
        </tr>
      </thead>
      <tbody>
        {% for w in workers %}
          <tr>
             <th scope="row"> {{w.id}} </th>
             <td> {{w.username}} </td>
             <td> {{w.num_anns}} </td>
             <td> {{w.date_joined}} </td>
          <tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
  </div>
</div>


{% endblock %}

CMU-Crowd/main/templates/main/admins/panel.html
{% extends 'base.html' %}
{% block title %}Admin Panel{% endblock %}
{% block content %}
<h1 class="text-center"> {{request.user.username}}'s Admin Panel</h1>
<h3 class="text-center"> You have {{active_job_count}} job(s) currently released. </h3>
<hr />

{% endblock %}

CMU-Crowd/main/templates/main/admins/update_job.html
{% extends 'base.html' %}
{% block title %}Update Job{% endblock %}

{% block content %}
  {% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for error in form.non_field_errors %}
        <p {% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}

<div class="container">
  <div class="row">
    <div class="col">
      <h2> Update Job </h2>
    </div>
  </div>
  {% include 'main/admins/job_form.html' %}
</div>
{% endblock %}

CMU-Crowd/main/templates/main/admins/view_batches.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}View Batches{% endblock %}
{% block content %}
<h1 class="text-center"> Manage Jobs / Batches </h1>
<hr />
<div class="container">
{% for job_name,batches in batches.items %}
	<div class="row">
		<div class="col">
			<span class="inline h2"> {{job_name}} </span> 
			<a href="{% url 'admins:update_job' jobs|get_item:job_name %}" class="btn btn-secondary mb-3"> Update </a>  
			{% if not batches %}
			<a  href=" {% url 'admins:delete_job' jobs|get_item:job_name %}" class="btn btn-danger mb-3">  Delete </a>
			{% endif %}
		</div>
	</div>

	<div class="row">
		<div class="col">
			<table class="table">
				<thead>
					<tr>
						<th> ID </th>
						<th> Number of HITs </th>
						<th> Created Date </th>
						<th> % Completed </th>
						<th> Status </th>
						<th> Cancel/Restart </th>
					</tr>
				</thead>
				<tbody>
					{%for batch in batches %}
						<tr>
            				<th scope="row"> {{batch.id}} </th>
             				<td> {{batch.num_HITs}}</td>
            				<td> {{batch.created_date}} </td>
            				<td> {{batch.percent_completion|floatformat:2 }} </td>
            				<td> <span class="badge badge-pill badge-{{batch.status_class}}"> _____ </span> </td>
            				<td>
        					{% if not batch.completed %}
        						{% if not batch.cancelled %}
        						<form action="{% url 'admins:update_batch' batch.id %}" method="post">
        						<input type="hidden" name="action" value="cancel" />
        						<input class="btn-xs btn-danger" type="submit" value="Cancel" />
        						{% elif batch.cancelled %}
        						<form action="{% url 'admins:update_batch' batch.id %}" method="post">
        						<input type="hidden" name="action" value="restart" />
        						<input class="btn-xs btn-success" type="submit" value="Restart" />
        							{% endif %}
        							{% csrf_token %}
        						</form>
        					{% endif %}
      						</td>
         				<tr>
					{% endfor %}
		 		</tbody>
		</table>
{% endfor %}
		</div>
	</div>


<script>
 function setStatusText() {
 	// Sets status text based on batch.status_class 
 	badges = document.getElementsByClassName('badge-pill');
 	for (let badge of badges) {
 		classes = badge.className.split(' ');
 		if (classes.includes('badge-primary')) {
 			badge.innerText = 'Active';
 		} else if (classes.includes('badge-danger')) {
 			badge.innerText = 'Cancelled';
 		} else if (classes.includes('badge-success')) {
 			badge.innerText = 'Completed';
 		}
 	}
 }

setStatusText()
</script>

{% endblock %}