CMU-Crowd/CMU-Crowd/urls.py
from django.contrib import admin
from django.urls import include, path
from main.views import main, workers, admins

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', main.SignUpView.as_view(), name='signup'),
    path('accounts/signup/worker/', workers.WorkerSignUpView.as_view(), name='worker_signup'),
    path('accounts/signup/admin/', admins.AdminSignUpView.as_view(), name='admin_signup'),
    path('admin/', admin.site.urls),
]

CMU-Crowd/main/urls.py
from django.urls import include, path
from .views import main, workers, admins
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", main.home, name='home'),
    path('workers/', include(([
        path('', workers.dash, name='dash'),
        path('view_annotations', workers.view_annotations, name='view_annotations'),
        path('view_jobs', workers.view_jobs, name='view_jobs'),
        path('jobs/<job_id>', workers.jobs, name="jobs")
    ], 'main'), namespace='workers')),
    path('admins/', include(([
        path('', admins.panel, name='panel'),
        path('job/add/', admins.JobCreateView.as_view(), name="create_job"),
        path('job/update/<int:pk>', admins.JobUpdateView.as_view(), name='update_job'),
        path('job/delete/<int:pk>', admins.JobDeleteView.as_view(), name='delete_job'),
        path('batch/start/', admins.BatchCreateView.as_view(), name="start_batch"),
        path('batches', admins.view_batches, name="view_batches"),
        path('update_batch/<batch_id>', admins.update_batch, name="update_batch"),
        path('manage_workers', admins.manage_workers, name="manage_workers")
    ], 'main'), namespace='admins')),

]


if settings.DEBUG: #development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CMU-Crowd/templates/admin_navbar.html
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">CMU-Crowd</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="{%url 'admins:create_job' %}"> Create A Job <span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item ">
              <a class="nav-link" href="{%url 'admins:start_batch' %}"> Start Batch </a>
            </li>
             <li class="nav-item ">
              <a class="nav-link" href="{% url 'admins:view_batches' %}">  Manage Jobs / Batches </a>
            </li>
             <li class="nav-item ">
              <a class="nav-link" href="{% url 'admins:manage_workers' %}"> Manage Workers </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link disabled" href="{%url 'logout' %}"> Logout </a>
            </li>
          </ul>
        </div>
      </nav>

CMU-Crowd/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title> {% block title %} CMU Crowd {% endblock %}</title>
 <script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<style>
/* Sticky footer styles
-------------------------------------------------- */
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px; /* Margin bottom by footer height */
  padding-top: 65px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px; /* Set the fixed height of the footer here */
  line-height: 60px; /* Vertically center the text there */
  background-color: #f5f5f5;
}

</style>
</head>

<body>
        <header>
          {% if request.user.is_authenticated %}
            {% if request.user.is_worker %}
               {% include 'worker_navbar.html' %}
            {% elif request.user.is_admin %}
              {% include 'admin_navbar.html' %}
            {% endif %}

          {% else %}
           {% include 'base_navbar.html' %}
          {% endif %}
    </header>

  <main role="main">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="footer navbar-fixed-bottom">
    <div class="container">
    <font size="1em">
      This site was built using <a href="https://github.com/A2Zadeh/CMU-Crowd">CMU-Crowd</a>, developed  by the <a href="http://multicomp.cs.cmu.edu">Multimodal Communication and Machine Learning Lab (Multicomp Lab)</a>, part of the <a href="https://www.lti.cs.cmu.edu/">Language Technologies Institute</a> in the <a href="http://scs.cmu.edu/">School of Computer Science</a> at <a href="http://cmu.edu">Carnegie Mellon University</a>. </font>
    </div>
  </footer>
</body>
</html>

CMU-Crowd/templates/base_navbar.html
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">CMU-Crowd</a>
  </nav>
 

CMU-Crowd/templates/worker_navbar.html
 <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">CMU-Crowd</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{%url 'workers:view_jobs' %}">Browse Available Jobs <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item  active">
              <a class="nav-link" href="{%url 'workers:view_annotations' %}"> View Submitted Work</a>
            </li>
            <li class="nav-item  active">
              <a class="nav-link disabled" href="{%url 'logout' %}"> Logout </a>
            </li>
          </ul>
        </div>
      </nav>